import "~/styles/globals.css";

import { Red_Hat_Display, Red_Hat_Text } from "next/font/google";

const textFont = Red_Hat_Text({
    subsets: ["latin"],
    variable: "--font-sans",
});
const displayFont = Red_Hat_Display({
    subsets: ["latin"],
    variable: "--font-display",
});

export const metadata = {
    title: "Ikaro Souza | Engenheiro Full Stack",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="pt-BR">
            <body
                className={`font-sans ${textFont.variable} ${displayFont.variable} bg-neutral-50 text-black dark:bg-neutral-900 dark:text-white`}
            >
                {children}
            </body>
        </html>
    );
}
